-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 13:35:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imdb` DEFAULT CHARACTER SET utf8 ;
USE `imdb` ;

-- -----------------------------------------------------
-- Table `imdb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE `imdb`.`USUARIO`;
CREATE TABLE IF NOT EXISTS `imdb`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb`.`FILMES`
-- -----------------------------------------------------
DROP TABLE `imdb`.`FILMES`;
CREATE TABLE IF NOT EXISTS `imdb`.`FILMES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NOT NULL,
  `diretor` VARCHAR(60) NOT NULL,
  `ano` INT UNSIGNED NOT NULL,
  `duracao` INT UNSIGNED NOT NULL,
  `sinopse` VARCHAR(500) NOT NULL,
  `origem` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb`.`AVALIACAO`
-- -----------------------------------------------------
DROP TABLE `imdb`.`AVALIACAO`;
CREATE TABLE IF NOT EXISTS `imdb`.`AVALIACAO` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USUARIO_id` INT NOT NULL,
  `FILMES_id` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`id`, `USUARIO_id`, `FILMES_id`),
  INDEX `fk_TB_USUARIO_has_TB_TRAB_ART_TB_TRAB_ART1_idx` (`FILMES_id` ASC),
  INDEX `fk_TB_USUARIO_has_TB_TRAB_ART_TB_USUARIO_idx` (`USUARIO_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_TB_USUARIO_has_TB_TRAB_ART_TB_USUARIO`
    FOREIGN KEY (`USUARIO_id`)
    REFERENCES `imdb`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_USUARIO_has_TB_TRAB_ART_TB_TRAB_ART1`
    FOREIGN KEY (`FILMES_id`)
    REFERENCES `imdb`.`FILMES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;