# --- !Ups

-- MySQL Script generated by MySQL Workbench
-- sex 09 jun 2017 11:45:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imdb` DEFAULT CHARACTER SET utf8 ;
USE `imdb` ;

-- -----------------------------------------------------
-- Table `imdb`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdb`.`TB_USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb`.`TB_TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdb`.`TB_TIPO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb`.`TB_TRAB_ART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdb`.`TB_TRAB_ART` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TB_TIPO_id` INT NOT NULL,
  `titulo` VARCHAR(60) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(35) NOT NULL,
  `ano` INT(4) UNSIGNED NOT NULL,
  `origem` VARCHAR(5) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `duracao` INT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `TB_TIPO_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_TB_TRAB_ART_TB_TIPO1_idx` (`TB_TIPO_id` ASC),
  CONSTRAINT `fk_TB_TRAB_ART_TB_TIPO1`
    FOREIGN KEY (`TB_TIPO_id`)
    REFERENCES `imdb`.`TB_TIPO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb`.`TB_AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdb`.`TB_AVALIACAO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TB_USUARIO_id` INT NOT NULL,
  `TB_TRAB_ART_id` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`id`, `TB_USUARIO_id`, `TB_TRAB_ART_id`),
  INDEX `fk_TB_USUARIO_has_TB_TRAB_ART_TB_TRAB_ART1_idx` (`TB_TRAB_ART_id` ASC),
  INDEX `fk_TB_USUARIO_has_TB_TRAB_ART_TB_USUARIO_idx` (`TB_USUARIO_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_TB_USUARIO_has_TB_TRAB_ART_TB_USUARIO`
    FOREIGN KEY (`TB_USUARIO_id`)
    REFERENCES `imdb`.`TB_USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_USUARIO_has_TB_TRAB_ART_TB_TRAB_ART1`
    FOREIGN KEY (`TB_TRAB_ART_id`)
    REFERENCES `imdb`.`TB_TRAB_ART` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--CREATE TABLE TB_FILME (
-- ID INTEGER NOT NULL AUTO_INCREMENT,
--  TITULO VARCHAR(50),
--  DIRETOR VARCHAR(50),
--  ANO_PRODUCAO INTEGER(4),
--  PRIMARY KEY (ID)
--);

# --- !Downs

DROP TABLE User;